### ISSUE TITLE
同样的文件，不同的效果

### ISSUE THREAD

**Issue by Epilepsy-YDF** [DONGChuan/Yummy-Jekyll#12]
我的主页是直接把你的网站里面的所有东西下载然后改了点东西之后push上来的，为什么差距这么大！！！！看我主页[http://epilepsy-ydf.github.io](url)

**Comment by DONGChuan** [comment]
@Epilepsy-YDF 你忘记上传依赖啦 ~ 你要把本地的 bower_components 文件夹也上传上去 ~

**Comment by Epilepsy-YDF** [comment]
本地有bower_components么？

**Comment by Epilepsy-YDF** [comment]
好吧还有一个问题，我在_config.yml里填的Google Analytics ID是没错的，可是打开网站之后查看源代码，发现ID不对。。。。

**Comment by DONGChuan** [comment]
@Epilepsy-YDF 你有按照说明运行 
![image](https://cloud.githubusercontent.com/assets/2586841/17175355/66c46b08-5407-11e6-97fa-5ca7fd1d2d4f.png)

这2个命令会下载你需要的依赖并放在 bower_components 文件夹里.

**Comment by DONGChuan** [comment]
Google Analytics ID 那里是一个BUG 我现在修复下

**Comment by DONGChuan** [comment]
@Epilepsy-YDF  Google Analytics ID 修复了。你从主库更新下代码看看

**Comment by LM450N** [comment]
The others contributors can't follow issues in Chinese. At least, write the title in English please.

**Comment by DONGChuan** [comment]
@LM450N You are right, I will pay attention about it :D  Thanks for reminding
