### ISSUE TITLE
希望_posts里面可以根据年份/月份分目录

### ISSUE THREAD

**Issue by ityouknow** [DONGChuan/Yummy-Jekyll#17]
博客模版很漂亮，我已经拿走搭建了自己的博客，但是在使用中我又一个小小的建议，是否可以在_posts里面按照年份来分一下目录，如果对一个博客输出量很多的人来讲，一年100多篇，回头在继续写博客的时候这里面的文件就太多了。

**Comment by DONGChuan** [comment]
嗯 我这几天看一下. 我也一直想加这个功能. 最近找到国内的工作了, 一直在忙回国的事.

**Comment by ityouknow** [comment]
欢迎回家 :)

**Comment by Epilepsy-YDF** [comment]
欢迎回家+`10086s`

**Comment by DONGChuan** [comment]
@ityouknow @Epilepsy-YDF 关于这个问题我研究了下, 貌似可以自己直接创建文件夹去分类, 不用改其他配置， 参考下 https://github.com/DONGChuan/DONGChuan.github.io/tree/master/_posts
我只是添加了2015 2016文件夹.然后把文章放进去.  你们也测试下看看

**Comment by ityouknow** [comment]
我刚测试了一下，目录包括中文、英文、数字或者相互嵌套都是可以按照时间顺序来展示的，看来是遍历了整个目录，比较赞。

**Comment by Yanqh** [comment]
欢迎回家+10086

**Comment by DONGChuan** [comment]
谢谢 ~不过以后要搞源生移动开发了 ~
