### ISSUE TITLE
Layout of directory presentation card broken

### ISSUE THREAD

**Issue by LM450N** [DONGChuan/Yummy-Jekyll#18]
In the "Open-Source" section, when the directory title is too long, the layout of the presentation card is broken.

<img width="1189" alt="capture d ecran 2016-08-16 a 02 06 26" src="https://cloud.githubusercontent.com/assets/2325091/17683860/e69b7476-6356-11e6-9c20-6501889889f0.png">

Also on the front  page at the right column.
<img width="565" alt="capture d ecran 2016-08-16 a 02 06 01" src="https://cloud.githubusercontent.com/assets/2325091/17683859/e68ce35c-6356-11e6-8b5c-47b13a119139.png">

**Comment by DONGChuan** [comment]
It's a little hard to fix it here. With "_" in the name, this long string will be considered as a single word. The only solution for the moment is to add a function to split this long string by "_" into different words. What do you think about this idea?

**Comment by LM450N** [comment]
You can check the result on [my own blog](https://louchart-mason.fr/open-source.html).

<img width="449" alt="capture d ecran 2016-08-17 a 00 34 28" src="https://cloud.githubusercontent.com/assets/2325091/17718114/7774ba00-6412-11e6-8285-50d428b36575.png">
<img width="780" alt="capture d ecran 2016-08-17 a 00 34 41" src="https://cloud.githubusercontent.com/assets/2325091/17718115/77766b48-6412-11e6-9fae-b44eb0333cc8.png">

**Comment by DONGChuan** [comment]
Thanks for your fix!! Add you in contributor list

**Comment by LM450N** [comment]
Oh?! Thank you 😄
