### ISSUE TITLE
Useless information on about-me page

### ISSUE THREAD

**Issue by LM450N** [DONGChuan/Yummy-Jekyll#19]
On the _"About"_ page, at the _"Contact"_ section, the visitor can see two information which are email and Website. The second one is wrong (the link is pointing to the GitHub account) and useless (the visitor is already on the website).

<img width="297" alt="capture d ecran 2016-08-16 a 02 15 43" src="https://cloud.githubusercontent.com/assets/2325091/17684055/9e64811e-6358-11e6-9880-b4cfb7439998.png">

**Comment by LM450N** [comment]
Sorry, I messed up with my directory and I had to manipulate the history to separate my configuration. 😴

**Comment by DONGChuan** [comment]
Merged! Thanks for your fix!!
