### ISSUE TITLE
The navbar animation makes me feel epileptic

### ISSUE THREAD

**Issue by LM450N** [DONGChuan/Yummy-Jekyll#22]
The animation of the navigation bar in a post makes me feel epileptic. During the transitions, the color of the text and background are both white, and the menu seems disappeared. I think it could be more "beautiful" by removing the transition.

### With transition
Original version.
![post-nav-bar-animation](https://cloud.githubusercontent.com/assets/2325091/17836563/57bf785c-6797-11e6-8f6d-395ae804bc57.gif)

### Without transition
Only the animation is disabled.
![post-nav-bar-animation-without-transition](https://cloud.githubusercontent.com/assets/2325091/17836577/c0567690-6797-11e6-9514-7b7d21ad09e0.gif)

### Without animation + different color
The animation is disabled and the background color is the same as the left border color.
![post-nav-bar-animation-without-transition-with-different-color](https://cloud.githubusercontent.com/assets/2325091/17836600/54cef04a-6798-11e6-8d88-22b65698748d.gif)

### Without animation + interchanged colors
The animation is disabled and the menu background and text colors are interchanged.
![post-nav-bar-animation-without-transition-and-twiced-colors](https://cloud.githubusercontent.com/assets/2325091/17836624/ff10f256-6798-11e6-91c4-b6bfdea24230.gif)

I think at least the animation must be removed. About the colors, pick those you prefer.

**Comment by DONGChuan** [comment]
Yeh. You are right. I prefer the last one "Without animation + interchanged colors", which one do you prefer?

**Comment by LM450N** [comment]
The two last are fine (no preference).

**Comment by DONGChuan** [comment]
I did a quick updates. Thanks for your suggestion :D

**Comment by LM450N** [comment]
But you only have changed the color. The issue is more related to [the transformation](https://github.com/DONGChuan/Yummy-Jekyll/blob/master/assets/css/sidebar-post-nav.css#L13-L15). I think you forgot to remove it.

**Comment by DONGChuan** [comment]
Yeh! You are right! I mixed with my own sites files :(

**Comment by LM450N** [comment]
👍 Thank you!
