### ISSUE TITLE
Menu of articles works only when user clicks on the name

### ISSUE THREAD

**Issue by LM450N** [DONGChuan/Yummy-Jekyll#24]
As you can see with the GIF, when the user clicks beside the menu option the action is not triggered and the page does not move to the selected section.

![directory-menu-link](https://cloud.githubusercontent.com/assets/2325091/17944726/3476cc72-6a41-11e6-9ab7-c10fb1e1945e.gif)

**Comment by DONGChuan** [comment]
Thanks! My bad!

**Comment by LM450N** [comment]
The issue was closed but the PR #25 is not merged.

**Comment by DONGChuan** [comment]
My bad. Sorry for late. I just changed my job . Will return back to China for my new job (For android/ios). So quite busy for the moment to prepare leave a country to another :D
