### ISSUE TITLE
Jekyll Serve Fails (undefined method 'sort')

### ISSUE THREAD

**Issue by msolters** [DONGChuan/Yummy-Jekyll#3]
I clone this repo, then ran `bundle install`.  When I try `bundle exec jekyll serve`, this is the console output:

```bash
msolters@samus:~/Downloads/Yummy-Jekyll$ bundle exec jekyll serve
Configuration file: /home/msolters/Downloads/Yummy-Jekyll/_config.yml
            Source: .
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
  Liquid Exception: undefined method `sort' for false:FalseClass in _includes/about.html, included in about.md
jekyll 3.0.1 | Error:  undefined method `sort' for false:FalseClass
```

**Comment by msolters** [comment]
This seems to be resolved after re-installing Ruby using RVM, e.g.

```bash
curl -L https://get.rvm.io | bash -s stable --autolibs=enabled --ruby
```

Which gives Ruby 2.3.0.

**Comment by KevinDiamen** [comment]
上面这个问题我解决了 又出现一个新问题
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'bundler' (>= 0) among 19 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/bin/bundle:22:in `<main>'
不知道什么问题

**Comment by DONGChuan** [comment]
@KevinDiamen 应该是环境的问题。如果你先确定看看是否已经安装好了 bundler。然后在看一看它在不在PATH变量里。 

再参考下这个解答 http://stackoverflow.com/questions/6166081/could-not-find-bundler-error

**Comment by leopardpan** [comment]
@KevinDiamen 你是怎么解决的？ 我运行 `curl -L https://get.rvm.io | bash -s stable --autolibs=enabled --ruby`  命令 , 还是包错误： `  Liquid Exception: undefined method `sort' for false:FalseClass in _includes/about.html, included in about.md`

**Comment by ajinkyakolhe112** [comment]
@msolters: I have the same issue and it is not solved by doing curl -L https://get.rvm.io | bash -s stable --autolibs=enabled --ruby

**Comment by litbai** [comment]
I have the same issue. I reinstalled the ruby 2.3.0 and jekyll and all, but still Liquid Exception: undefined method `sort' for false:FalseClass in about.md

**Comment by debragail** [comment]
we're having this issue too

**Comment by harbby** [comment]
me too
