### ISSUE TITLE
jekyll 3.0.1 | Error:  undefined method `sort' for false:FalseClass

### ISSUE THREAD

**Issue by xinerd** [DONGChuan/Yummy-Jekyll#31]
sort problem still exists. 

> Liquid Exception: undefined method `sort' for false:FalseClass in _includes/about.html, included in about.md
jekyll 3.0.1 | Error:  undefined method `sort' for false:FalseClass

tried reinstall ruby

**Comment by DONGChuan** [comment]
@xinerd Because for the moment, the list you want to sort is NULL on your local!!! Have you tried pushed at least one time your website to the GitHub repo?

**Comment by xinerd** [comment]
understood, thanks for your explantation.

**Comment by ajinkyakolhe112** [comment]
@xinerd, I have the same issue. Can you please tell me how to solve it?

**Comment by xinerd** [comment]
@ajinkyakolhe112 Hi, have you tried the solution @DONGChuan mentioned above? 
I believe that it will solve the issue, just put at least one post into _post folder.
if the issue remains, let us know, thanks.

**Comment by ajinkyakolhe112** [comment]
@xinerd : Hi, I am trying jekyll for first time. Please help.
I have put 3 posts in _post but its still giving me same error. 
Can you please check it https://github.com/ajinkyakolhe112/ajinkyakolhe112.github.io

**Comment by ajinkyakolhe112** [comment]
@xinerd : I cloned your repository and its working perfectly now. Thanks. :)

**Comment by xinerd** [comment]
@ajinkyakolhe112 glad to hear you have started a new journey. happy posting.
