### ISSUE TITLE
对原作者的抱歉

### ISSUE THREAD

**Issue by yumemor** [DONGChuan/Yummy-Jekyll#37]
事情是这样的，最开始在无意中看见这个主题(不是作者的博客)，觉得非常的不错 在使用了一段时间的 Jekyll 觉得没有 Hexo 好用，于是就进行了移植 。

不过我一直不知道原作者是谁(主要是找错人了 )，今天这里才看见 这个主题的起源是这里 于是我更换了 1.0 的 README ，实在是抱歉！ 
 
> [Hexo-Theme-Primer](https://github.com/yumemor/hexo-theme-primer)

**Comment by DONGChuan** [comment]
@yumemor 这个创意我也不一定是真正的原作者, 我也是在哪看到类似的, 觉得很不错, 一直找不到模版, 就自学前端做了它, 结果现在一堆坑, 没时间好好修复 ..

Jekyll 感觉不稳定, 各个版本的兼容性也不好 (也可能是我前端水平不够). 我其实一开始是用 hexo 的, 只是那时候 hexo 还比较新, 感觉功能不丰富. 然后用了 jekyll ... 我之后再看看 hexo 如何啦.

点赞 搜索功能 ～ 一直想要. 然后你的主题 Blog Tags 有找到实现的可能了么？
最后谢谢支持 ～

**Comment by yumemor** [comment]
现在只是 Category 有实现 也是比较简单的实现 ，Tags 目前还没有，主要是没有遇上比较好的体验，所以就没动。

然后，我也不是专业的前端😄 我是做后端的 因为兴趣就学习了一部分
