### ISSUE TITLE
Fetching own public repositories on github

### ISSUE THREAD

**Issue by shahsaurabh0605** [DONGChuan/Yummy-Jekyll#4]
I was for a long time trying to get my own public repositories in `open-source` page but failed to do so. Then I figured out that I had to add this line : 
`repository: shahsaurabh0605/shahsaurabh0605.github.io` and it worked.

May be you should consider this.

**Comment by DONGChuan** [comment]
Hi. Thanks for your report.

I used "- jekyll-github-metadata" to get all meta information about github. According to this page, "https://github.com/jekyll/github-metadata", if you do not set yet the remote repo, it needs to set "repository". I will add this settings in _config.yml. Or if you want to send a quick PR? :D

**Comment by shahsaurabh0605** [comment]
I will send a PR

**Comment by DONGChuan** [comment]
PR merged! Thanks so much :+1:
