### ISSUE TITLE
Possible to hide post directory on certain posts?

### ISSUE THREAD

**Issue by sassigeek** [DONGChuan/Yummy-Jekyll#8]
Hi, firstly beautiful theme thank you so much for sharing. I was just wondering whether or not its possible or easy to hide the post directory sidebar from showing up on certain posts? I.e. some posts are so short and only 1 or maybe two paragraphs and just don't need this functionality. 

Thanks in advance. 

Jus.

**Comment by DONGChuan** [comment]
@sassigeek Hi Sassigeek. I could propose a solution for it. But the other thing to consider is, you want to leave the original sidebar area empty?  Or we could let the post to occupy the whole area if no sidebar?

**Comment by sassigeek** [comment]
If the post could occupy the whole page if no sidebar that would awesome. 👍

**Comment by DONGChuan** [comment]
Yeh. I agree with so. I will have a try to realize it this week. Should not be that hard.

**Comment by DONGChuan** [comment]
@sassigeek Hi. I did a small fix on it. Now you just need to set **no-post-nav:true** for your post

Example - https://github.com/DONGChuan/Yummy-Jekyll/blob/master/_posts/2016-05-14-Example-No-Sidebar-Nav.markdown
